In [21]:
#beautifulsoub no need for json api
import json
import requests
import pandas as pd

In [4]:
space_url="https://api.sofascore.com/api/v1/unique-tournament/1900/season/34713/standings/total"

In [5]:
r=requestsests.get(space_url)

In [6]:
json_object=json.loads(r.content)

In [7]:
json_object

{'standings': [{'tournament': {'name': 'Indian Super League',
    'slug': 'indian-super-league',
    'category': {'name': 'India',
     'slug': 'india',
     'sport': {'name': 'Football', 'slug': 'football', 'id': 1},
     'id': 352,
     'flag': 'india',
     'alpha2': 'IN'},
    'uniqueTournament': {'name': 'Indian Super League',
     'slug': 'indian-super-league',
     'category': {'name': 'India',
      'slug': 'india',
      'sport': {'name': 'Football', 'slug': 'football', 'id': 1},
      'id': 352,
      'flag': 'india',
      'alpha2': 'IN'},
     'userCount': 18428,
     'id': 1900},
    'id': 38566},
   'type': 'total',
   'name': 'Indian Super League',
   'descriptions': [],
   'tieBreakingRule': {'text': 'In the event that two (or more) teams have an equal number of points, the following rules break the tie during the season: 1. Goal difference 2. Goals scored At the end of the season, the following tie-breaking procedures are used: 1. Head-to-head 2. Goal difference 3. Goals scored',
    'id': 4},
   'rows': [{'team': {'name': 'Mumbai City FC',
      'slug': 'mumbai-city-fc',
      'shortName': 'Mumbai City',
      'gender': 'M',
      'userCount': 7643,
      'nameCode': 'MCI',
      'national': False,
      'type': 0,
      'id': 174600,
      'teamColors': {'primary': '#0000ff',
       'secondary': '#0000ff',
       'text': '#0000ff'}},
     'descriptions': [],
     'promotion': {'text': 'Playoffs', 'id': 6},
     'position': 1,
     'matches': 20,
     'wins': 12,
     'losses': 4,
     'draws': 4,
     'scoresFor': 35,
     'scoresAgainst': 18,
     'points': 40,
     'id': 541930},
    {'team': {'name': 'ATK Mohun Bagan FC',
      'slug': 'atk-mohun-bagan-fc',
      'shortName': 'ATK Mohun Bagan',
      'gender': 'M',
      'userCount': 6258,
      'nameCode': 'AMB',
      'national': False,
      'type': 0,
      'id': 370834,
      'teamColors': {'primary': '#91191b',
       'secondary': '#246a1d',
       'text': '#246a1d'}},
     'descriptions': [],
     'promotion': {'text': 'Playoffs', 'id': 6},
     'position': 2,
     'matches': 20,
     'wins': 12,
     'losses': 4,
     'draws': 4,
     'scoresFor': 28,
     'scoresAgainst': 15,
     'points': 40,
     'id': 544103},
    {'team': {'name': 'Northeast United',
      'slug': 'northeast-united',
      'shortName': 'Northeast Utd',
      'gender': 'M',
      'userCount': 4185,
      'nameCode': 'NUN',
      'national': False,
      'type': 0,
      'id': 174602,
      'teamColors': {'primary': '#ffffff',
       'secondary': '#ffffff',
       'text': '#ffffff'}},
     'descriptions': [],
     'promotion': {'text': 'Playoffs', 'id': 6},
     'position': 3,
     'matches': 20,
     'wins': 8,
     'losses': 3,
     'draws': 9,
     'scoresFor': 31,
     'scoresAgainst': 25,
     'points': 33,
     'id': 541931},
    {'team': {'name': 'FC Goa',
      'slug': 'fc-goa',
      'shortName': 'Goa',
      'gender': 'M',
      'userCount': 8452,
      'nameCode': 'GOA',
      'national': False,
      'type': 0,
      'id': 174594,
      'teamColors': {'primary': '#0033ff',
       'secondary': '#0033ff',
       'text': '#0033ff'}},
     'descriptions': [],
     'promotion': {'text': 'Playoffs', 'id': 6},
     'position': 4,
     'matches': 20,
     'wins': 7,
     'losses': 3,
     'draws': 10,
     'scoresFor': 31,
     'scoresAgainst': 23,
     'points': 31,
     'id': 541925},
    {'team': {'name': 'Hyderabad FC',
      'slug': 'hyderabad-fc',
      'shortName': 'Hyderabad',
      'gender': 'M',
      'userCount': 3056,
      'nameCode': 'HYD',
      'disabled': False,
      'national': False,
      'type': 0,
      'id': 331840,
      'teamColors': {'primary': '#0f141b',
       'secondary': '#f8ca1c',
       'text': '#f8ca1c'}},
     'descriptions': [],
     'position': 5,
     'matches': 20,
     'wins': 6,
     'losses': 3,
     'draws': 11,
     'scoresFor': 27,
     'scoresAgainst': 19,
     'points': 29,
     'id': 541926},
    {'team': {'name': 'Jamshedpur',
      'slug': 'jamshedpur',
      'shortName': 'Jamshedpur',
      'gender': 'M',
      'userCount': 3012,
      'nameCode': 'JAM',
      'national': False,
      'type': 0,
      'id': 267915,
      'teamColors': {'primary': '#eb2325',
       'secondary': '#000000',
       'text': '#000000'}},
     'descriptions': [],
     'position': 6,
     'matches': 20,
     'wins': 7,
     'losses': 7,
     'draws': 6,
     'scoresFor': 21,
     'scoresAgainst': 22,
     'points': 27,
     'id': 541927},
    {'team': {'name': 'Bengaluru FC',
      'slug': 'bengaluru-fc',
      'shortName': 'Bengaluru',
      'gender': 'M',
      'userCount': 6980,
      'nameCode': 'BEN',
      'national': False,
      'type': 0,
      'id': 118670,
      'teamColors': {'primary': '#0b062c',
       'secondary': '#000000',
       'text': '#000000'}},
     'descriptions': [],
     'position': 7,
     'matches': 20,
     'wins': 5,
     'losses': 8,
     'draws': 7,
     'scoresFor': 26,
     'scoresAgainst': 28,
     'points': 22,
     'id': 541923},
    {'team': {'name': 'Chennaiyin FC',
      'slug': 'chennaiyin-fc',
      'shortName': 'Chennaiyin',
      'gender': 'M',
      'userCount': 4651,
      'nameCode': 'CHE',
      'national': False,
      'type': 0,
      'id': 174590,
      'teamColors': {'primary': '#0000ff',
       'secondary': '#0000ff',
       'text': '#0000ff'}},
     'descriptions': [],
     'position': 8,
     'matches': 20,
     'wins': 3,
     'losses': 6,
     'draws': 11,
     'scoresFor': 17,
     'scoresAgainst': 23,
     'points': 20,
     'id': 541924},
    {'team': {'name': 'SC East Bengal',
      'slug': 'sc-east-bengal',
      'shortName': 'SC East Bengal',
      'gender': 'M',
      'userCount': 3974,
      'nameCode': 'EBC',
      'disabled': False,
      'national': False,
      'type': 0,
      'id': 40655,
      'teamColors': {'primary': '#ed1c24',
       'secondary': '#ffc90e',
       'text': '#ffc90e'}},
     'descriptions': [],
     'position': 9,
     'matches': 20,
     'wins': 3,
     'losses': 9,
     'draws': 8,
     'scoresFor': 22,
     'scoresAgainst': 33,
     'points': 17,
     'id': 541933},
    {'team': {'name': 'Kerala Blasters',
      'slug': 'kerala-blasters',
      'shortName': 'Blasters',
      'gender': 'M',
      'userCount': 10645,
      'nameCode': 'KBL',
      'disabled': False,
      'national': False,
      'type': 0,
      'id': 174598,
      'teamColors': {'primary': '#ffff00',
       'secondary': '#ffff00',
       'text': '#ffff00'}},
     'descriptions': [],
     'position': 10,
     'matches': 20,
     'wins': 3,
     'losses': 9,
     'draws': 8,
     'scoresFor': 23,
     'scoresAgainst': 36,
     'points': 17,
     'id': 541928},
    {'team': {'name': 'Odisha Football Club',
      'slug': 'odisha-football-club',
      'shortName': 'Odisha FC',
      'gender': 'M',
      'userCount': 2987,
      'nameCode': 'DDY',
      'national': False,
      'type': 0,
      'id': 174592,
      'teamColors': {'primary': '#ff6600',
       'secondary': '#ff6600',
       'text': '#ff6600'}},
     'descriptions': [],
     'position': 11,
     'matches': 20,
     'wins': 2,
     'losses': 12,
     'draws': 6,
     'scoresFor': 25,
     'scoresAgainst': 44,
     'points': 12,
     'id': 541932}],
   'id': 68782,
   'updatedAtTimestamp': 1607615921}]}

In [8]:
json_object.__len__()

1

In [10]:
json_object.keys()

dict_keys(['standings'])

In [13]:
json_object['standings']

[{'tournament': {'name': 'Indian Super League',
   'slug': 'indian-super-league',
   'category': {'name': 'India',
    'slug': 'india',
    'sport': {'name': 'Football', 'slug': 'football', 'id': 1},
    'id': 352,
    'flag': 'india',
    'alpha2': 'IN'},
   'uniqueTournament': {'name': 'Indian Super League',
    'slug': 'indian-super-league',
    'category': {'name': 'India',
     'slug': 'india',
     'sport': {'name': 'Football', 'slug': 'football', 'id': 1},
     'id': 352,
     'flag': 'india',
     'alpha2': 'IN'},
    'userCount': 18428,
    'id': 1900},
   'id': 38566},
  'type': 'total',
  'name': 'Indian Super League',
  'descriptions': [],
  'tieBreakingRule': {'text': 'In the event that two (or more) teams have an equal number of points, the following rules break the tie during the season: 1. Goal difference 2. Goals scored At the end of the season, the following tie-breaking procedures are used: 1. Head-to-head 2. Goal difference 3. Goals scored',
   'id': 4},
  'rows': [{'team': {'name': 'Mumbai City FC',
     'slug': 'mumbai-city-fc',
     'shortName': 'Mumbai City',
     'gender': 'M',
     'userCount': 7643,
     'nameCode': 'MCI',
     'national': False,
     'type': 0,
     'id': 174600,
     'teamColors': {'primary': '#0000ff',
      'secondary': '#0000ff',
      'text': '#0000ff'}},
    'descriptions': [],
    'promotion': {'text': 'Playoffs', 'id': 6},
    'position': 1,
    'matches': 20,
    'wins': 12,
    'losses': 4,
    'draws': 4,
    'scoresFor': 35,
    'scoresAgainst': 18,
    'points': 40,
    'id': 541930},
   {'team': {'name': 'ATK Mohun Bagan FC',
     'slug': 'atk-mohun-bagan-fc',
     'shortName': 'ATK Mohun Bagan',
     'gender': 'M',
     'userCount': 6258,
     'nameCode': 'AMB',
     'national': False,
     'type': 0,
     'id': 370834,
     'teamColors': {'primary': '#91191b',
      'secondary': '#246a1d',
      'text': '#246a1d'}},
    'descriptions': [],
    'promotion': {'text': 'Playoffs', 'id': 6},
    'position': 2,
    'matches': 20,
    'wins': 12,
    'losses': 4,
    'draws': 4,
    'scoresFor': 28,
    'scoresAgainst': 15,
    'points': 40,
    'id': 544103},
   {'team': {'name': 'Northeast United',
     'slug': 'northeast-united',
     'shortName': 'Northeast Utd',
     'gender': 'M',
     'userCount': 4185,
     'nameCode': 'NUN',
     'national': False,
     'type': 0,
     'id': 174602,
     'teamColors': {'primary': '#ffffff',
      'secondary': '#ffffff',
      'text': '#ffffff'}},
    'descriptions': [],
    'promotion': {'text': 'Playoffs', 'id': 6},
    'position': 3,
    'matches': 20,
    'wins': 8,
    'losses': 3,
    'draws': 9,
    'scoresFor': 31,
    'scoresAgainst': 25,
    'points': 33,
    'id': 541931},
   {'team': {'name': 'FC Goa',
     'slug': 'fc-goa',
     'shortName': 'Goa',
     'gender': 'M',
     'userCount': 8452,
     'nameCode': 'GOA',
     'national': False,
     'type': 0,
     'id': 174594,
     'teamColors': {'primary': '#0033ff',
      'secondary': '#0033ff',
      'text': '#0033ff'}},
    'descriptions': [],
    'promotion': {'text': 'Playoffs', 'id': 6},
    'position': 4,
    'matches': 20,
    'wins': 7,
    'losses': 3,
    'draws': 10,
    'scoresFor': 31,
    'scoresAgainst': 23,
    'points': 31,
    'id': 541925},
   {'team': {'name': 'Hyderabad FC',
     'slug': 'hyderabad-fc',
     'shortName': 'Hyderabad',
     'gender': 'M',
     'userCount': 3056,
     'nameCode': 'HYD',
     'disabled': False,
     'national': False,
     'type': 0,
     'id': 331840,
     'teamColors': {'primary': '#0f141b',
      'secondary': '#f8ca1c',
      'text': '#f8ca1c'}},
    'descriptions': [],
    'position': 5,
    'matches': 20,
    'wins': 6,
    'losses': 3,
    'draws': 11,
    'scoresFor': 27,
    'scoresAgainst': 19,
    'points': 29,
    'id': 541926},
   {'team': {'name': 'Jamshedpur',
     'slug': 'jamshedpur',
     'shortName': 'Jamshedpur',
     'gender': 'M',
     'userCount': 3012,
     'nameCode': 'JAM',
     'national': False,
     'type': 0,
     'id': 267915,
     'teamColors': {'primary': '#eb2325',
      'secondary': '#000000',
      'text': '#000000'}},
    'descriptions': [],
    'position': 6,
    'matches': 20,
    'wins': 7,
    'losses': 7,
    'draws': 6,
    'scoresFor': 21,
    'scoresAgainst': 22,
    'points': 27,
    'id': 541927},
   {'team': {'name': 'Bengaluru FC',
     'slug': 'bengaluru-fc',
     'shortName': 'Bengaluru',
     'gender': 'M',
     'userCount': 6980,
     'nameCode': 'BEN',
     'national': False,
     'type': 0,
     'id': 118670,
     'teamColors': {'primary': '#0b062c',
      'secondary': '#000000',
      'text': '#000000'}},
    'descriptions': [],
    'position': 7,
    'matches': 20,
    'wins': 5,
    'losses': 8,
    'draws': 7,
    'scoresFor': 26,
    'scoresAgainst': 28,
    'points': 22,
    'id': 541923},
   {'team': {'name': 'Chennaiyin FC',
     'slug': 'chennaiyin-fc',
     'shortName': 'Chennaiyin',
     'gender': 'M',
     'userCount': 4651,
     'nameCode': 'CHE',
     'national': False,
     'type': 0,
     'id': 174590,
     'teamColors': {'primary': '#0000ff',
      'secondary': '#0000ff',
      'text': '#0000ff'}},
    'descriptions': [],
    'position': 8,
    'matches': 20,
    'wins': 3,
    'losses': 6,
    'draws': 11,
    'scoresFor': 17,
    'scoresAgainst': 23,
    'points': 20,
    'id': 541924},
   {'team': {'name': 'SC East Bengal',
     'slug': 'sc-east-bengal',
     'shortName': 'SC East Bengal',
     'gender': 'M',
     'userCount': 3974,
     'nameCode': 'EBC',
     'disabled': False,
     'national': False,
     'type': 0,
     'id': 40655,
     'teamColors': {'primary': '#ed1c24',
      'secondary': '#ffc90e',
      'text': '#ffc90e'}},
    'descriptions': [],
    'position': 9,
    'matches': 20,
    'wins': 3,
    'losses': 9,
    'draws': 8,
    'scoresFor': 22,
    'scoresAgainst': 33,
    'points': 17,
    'id': 541933},
   {'team': {'name': 'Kerala Blasters',
     'slug': 'kerala-blasters',
     'shortName': 'Blasters',
     'gender': 'M',
     'userCount': 10645,
     'nameCode': 'KBL',
     'disabled': False,
     'national': False,
     'type': 0,
     'id': 174598,
     'teamColors': {'primary': '#ffff00',
      'secondary': '#ffff00',
      'text': '#ffff00'}},
    'descriptions': [],
    'position': 10,
    'matches': 20,
    'wins': 3,
    'losses': 9,
    'draws': 8,
    'scoresFor': 23,
    'scoresAgainst': 36,
    'points': 17,
    'id': 541928},
   {'team': {'name': 'Odisha Football Club',
     'slug': 'odisha-football-club',
     'shortName': 'Odisha FC',
     'gender': 'M',
     'userCount': 2987,
     'nameCode': 'DDY',
     'national': False,
     'type': 0,
     'id': 174592,
     'teamColors': {'primary': '#ff6600',
      'secondary': '#ff6600',
      'text': '#ff6600'}},
    'descriptions': [],
    'position': 11,
    'matches': 20,
    'wins': 2,
    'losses': 12,
    'draws': 6,
    'scoresFor': 25,
    'scoresAgainst': 44,
    'points': 12,
    'id': 541932}],
  'id': 68782,
  'updatedAtTimestamp': 1607615921}]

In [14]:
len(json_object)

1

In [16]:
len(json_object['standings'][0])

8

In [18]:
(json_object['standings'][0]).keys()

dict_keys(['tournament', 'type', 'name', 'descriptions', 'tieBreakingRule', 'rows', 'id', 'updatedAtTimestamp'])

In [24]:
df=pd.json_normalize((json_object['standings'][0]['rows']))

In [26]:
df

,descriptions,position,matches,wins,losses,draws,scoresFor,scoresAgainst,points,id,...,team.nameCode,team.national,team.type,team.id,team.teamColors.primary,team.teamColors.secondary,team.teamColors.text,promotion.text,promotion.id,team.disabled
0,[],1,20,12,4,4,35,18,40,541930,...,MCI,False,0,174600,#0000ff,#0000ff,#0000ff,Playoffs,6.0,NaN
1,[],2,20,12,4,4,28,15,40,544103,...,AMB,False,0,370834,#91191b,#246a1d,#246a1d,Playoffs,6.0,NaN
2,[],3,20,8,3,9,31,25,33,541931,...,NUN,False,0,174602,#ffffff,#ffffff,#ffffff,Playoffs,6.0,NaN
3,[],4,20,7,3,10,31,23,31,541925,...,GOA,False,0,174594,#0033ff,#0033ff,#0033ff,Playoffs,6.0,NaN
4,[],5,20,6,3,11,27,19,29,541926,...,HYD,False,0,331840,#0f141b,#f8ca1c,#f8ca1c,NaN,NaN,False
5,[],6,20,7,7,6,21,22,27,541927,...,JAM,False,0,267915,#eb2325,#000000,#000000,NaN,NaN,NaN
6,[],7,20,5,8,7,26,28,22,541923,...,BEN,False,0,118670,#0b062c,#000000,#000000,NaN,NaN,NaN
7,[],8,20,3,6,11,17,23,20,541924,...,CHE,False,0,174590,#0000ff,#0000ff,#0000ff,NaN,NaN,NaN
8,[],9,20,3,9,8,22,33,17,541933,...,EBC,False,0,40655,#ed1c24,#ffc90e,#ffc90e,NaN,NaN,False
9,[],10,20,3,9,8,23,36,17,541928,...,KBL,False,0,174598,#ffff00,#ffff00,#ffff00,NaN,NaN,False
10,[],11,20,2,12,6,25,44,12,541932,...,DDY,False,0,174592,#ff6600,#ff6600,#ff6600,NaN,NaN,NaN

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   descriptions               11 non-null     object
 1   position                   11 non-null     int64
 2   matches                    11 non-null     int64
 3   wins                       11 non-null     int64
 4   losses                     11 non-null     int64
 5   draws                      11 non-null     int64
 6   scoresFor                  11 non-null     int64
 7   scoresAgainst              11 non-null     int64
 8   points                     11 non-null     int64
 9   id                         11 non-null     int64
 10  team.name                  11 non-null     object
 11  team.slug                  11 non-null     object
 12  team.shortName             11 non-null     object
 13  team.gender                11 non-null     object
 14  team.userCount             11 non-null     int64
 15  team.nameCode              11 non-null     object
 16  team.national              11 non-null     bool
 17  team.type                  11 non-null     int64
 18  team.id                    11 non-null     int64
 19  team.teamColors.primary    11 non-null     object
 20  team.teamColors.secondary  11 non-null     object
 21  team.teamColors.text       11 non-null     object
 22  promotion.text             4 non-null      object
 23  promotion.id               4 non-null      float64
 24  team.disabled              3 non-null      object
dtypes: bool(1), float64(1), int64(12), object(11)
memory usage: 2.2+ KB

ModuleNotFoundError: No module named 'files'